### ISSUE TITLE
책 상세화면 구현

### ISSUE THREAD

**Issue by suri0000** [suri0000/BookShelf#5]
## 🛠 Issue
- 책 상세화면 구현

## 📝 To-do
- [ ] 검색 결과 셀 누르면 detailview 모달로 뜨게
- [ ] 누른 셀에 알맞은 책 데이터 넣어주기
- [ ] 담기 누르면 담은 책 목록 화면에서 볼 수 있게
- [ ] 담기 누르면 모달 닫기
- [ ] X 버튼을 탭 하면 모달 닫기

#### 선택구현
- [ ] 책 상세 화면은 컨텐츠 양에 따라 스크롤 가능합니다.
- [ ] 담기 및 X 버튼은 플로팅 버튼입니다.
- [ ] 모달이 닫힌 이후, 책 검색 화면에서 `[…]책 담기 완료!` 라는 알림창을 보여줍니다.
