### ISSUE TITLE
담은 책 목록 화면

### ISSUE THREAD

**Issue by suri0000** [suri0000/BookShelf#7]
## 🛠 Issue
- 담은 책 목록 구현(ListOfBooks)

## 📝 To-do
- [x] CoreData 설정
- [x] 담은 책 목록 UI
- [x] 담기 누르면 담은 책 목록 화면에서 볼 수 있게
- [x] 전체 삭제 버튼
- [x] 개별삭제

#### 선택구현
- [ ] 모달이 닫힌 이후, 책 검색 화면에서 `[…]책 담기 완료!` 라는 알림창을 보여줍니다.
- [ ] 추가 버튼을 누르면 첫번째 탭을 보여주고, 서치바를 활성화시킵니다.
